import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "tr" | "ru";

interface TranslationValues {
  readonly [key: string]: string | number;
}

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  availableLanguages: Array<{ value: Language; label: string }>;
  t: (key: string, options?: { defaultValue?: string; values?: TranslationValues }) => string;
}

const STORAGE_KEY = "offline-stock-language";

const languageLabels: Record<Language, string> = {
  en: "English",
  tr: "Türkçe",
  ru: "Русский",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "common.cancel": "Cancel",
    "app.name": "Offline Stock App",
    "app.tagline": "Inventory & sales management for local shops",
    "app.initializing": "Initializing database...",
    "nav.depot": "Depot",
    "nav.sales": "Sales",
    "nav.customers": "Customers",
    "nav.shopping": "Shopping",
    "nav.history": "History",
    "nav.settings": "Settings",
    "layout.theme": "Theme",
    "layout.language": "Language",
    "layout.defaultTitle": "Magazin Proekt",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "language.english": "English",
    "language.turkish": "Türkçe",
    "language.russian": "Русский",
    "login.title": "Offline Stock App",
    "login.subtitle": "Sign in with your nickname and password to continue.",
    "login.nickname": "Nickname",
    "login.nickname.placeholder": "Enter your nickname",
    "login.password": "Password",
    "login.password.placeholder": "Enter your password",
    "login.remember": "Remember me on this device",
    "login.submit": "Sign in",
    "login.submitting": "Signing in...",
    "login.signup.question": "Need an account?",
    "login.signup.link": "Sign up",
    "login.validation": "Nickname and password are required",
    "signup.title": "Create an account",
    "signup.subtitle": "Set your admin credentials to secure the store.",
    "signup.nickname": "Nickname",
    "signup.nickname.placeholder": "Choose a nickname",
    "signup.password": "Password",
    "signup.password.placeholder": "Choose a password",
    "signup.confirmPassword": "Confirm password",
    "signup.confirmPassword.placeholder": "Re-enter password",
    "signup.submit": "Create account",
    "signup.submitting": "Creating account...",
    "signup.haveAccount": "Already have an account?",
    "signup.login": "Sign in",
    "signup.passwordMismatch": "Passwords do not match",
    "signup.validation": "Nickname and password are required",
    "signup.passwordLength": "Password must be at least 6 characters long",
    "depot.title": "Magazin Proekt",
    "depot.search.placeholder": "Search products...",
    "depot.add": "Add",
    "depot.addProduct": "Add Product",
    "depot.editProduct": "Edit Product",
    "depot.form.name": "Name",
    "depot.form.barcode": "Barcode/SKU",
    "depot.form.category": "Category",
    "depot.form.buyPrice": "Buy Price",
    "depot.form.sellPrice": "Sell Price",
    "depot.form.quantity": "Quantity",
    "depot.form.minStock": "Min Stock",
    "depot.form.save": "Save",
    "depot.export": "Export",
    "depot.export.filename": "inventory",
    "depot.export.sheetName": "Products",
    "depot.filter.all": "All",
    "depot.filter.category": "Category",
    "depot.filter.searchPlaceholder": "Search categories...",
    "depot.filter.noResults": "No categories found",
    "depot.filter.uncategorized": "Uncategorized",
    "depot.actions.deleteAll": "Delete all products",
    "depot.badge.low": "Low",
    "depot.price.buy": "Buy:",
    "depot.price.sell": "Sell:",
    "depot.totals.buy": "Total buy",
    "depot.totals.sell": "Total sell",
    "depot.totals.monthSelector": "Sales month",
    "depot.totals.clearMonth": "Show all",
    "depot.totals.monthlySales": "Monthly sales",
    "depot.stock": "in stock",
    "depot.empty": "No products found",
    "depot.toast.added": "Product added successfully",
    "depot.toast.updated": "Product updated successfully",
    "depot.toast.savedError": "Failed to save product",
    "depot.toast.increased": "Stock increased",
    "depot.toast.decreased": "Stock decreased",
    "depot.toast.deleted": "Product removed",
    "depot.toast.allDeleted": "All products removed",
    "depot.toast.noProductsToDelete": "There are no products to delete.",
    "depot.toast.noExport": "No products to export",
    "depot.confirm.delete": "Delete the product \"{name}\"?",
    "depot.confirm.deleteAll": "Delete all products and detach them from shopping lists? This cannot be undone.",
    "depot.export.name": "Name",
    "depot.export.barcode": "Barcode",
    "depot.export.category": "Category",
    "depot.export.buyPrice": "Buy Price",
    "depot.export.sellPrice": "Sell Price",
    "depot.export.quantity": "Quantity",
    "depot.export.minStock": "Minimum Stock",
    "sales.title": "Sales",
    "sales.searchProducts": "Search products...",
    "sales.openCatalog": "Add products",
    "sales.cartSearch": "Search cart...",
    "sales.cart": "Cart",
    "sales.noItems": "No items in cart",
    "sales.totals": "Totals",
    "sales.total": "Total",
    "sales.paid": "Paid",
    "sales.debt": "Debt",
    "sales.saleType": "Sale type",
    "sales.saleType.paid": "Fully paid",
    "sales.saleType.debt": "Debt",
    "sales.customer": "Customer",
    "sales.customer.select": "Select customer",
    "sales.customer.new": "Add new customer",
    "sales.customer.none": "No customers found",
    "sales.newCustomer.title": "New customer",
    "sales.newCustomer.name": "Name",
    "sales.newCustomer.phone": "Phone",
    "sales.newCustomer.notes": "Notes",
    "sales.newCustomer.submit": "Create",
    "sales.newCustomer.cancel": "Cancel",
    "sales.complete": "Complete sale",
    "sales.clear": "Clear cart",
    "sales.toast.noStock": "Not enough stock",
    "sales.toast.added": "Added to cart",
    "sales.toast.nameRequired": "Customer name is required",
    "sales.toast.created": "Customer created successfully",
    "sales.toast.createError": "Failed to create customer",
    "sales.toast.empty": "Cart is empty",
    "sales.toast.customerRequired": "Select a customer for debt sales",
    "sales.toast.failed": "Failed to complete sale",
    "sales.toast.completed": "Sale recorded successfully",
    "sales.debtNote": "Debt sales require assigning a customer and will be tracked until fully paid.",
    "sales.customerTotal": "Total for {name}",
    "sales.unitPrice": "{price} each",
    "sales.priceLabel": "Price",
    "sales.noMatches": "No cart items match your search.",
    "sales.receipt.title": "Sale receipt",
    "sales.receipt.customer": "Customer",
    "sales.receipt.date": "Date",
    "sales.receipt.cashier": "Cashier",
    "sales.receipt.items": "Items",
    "sales.receipt.total": "Total",
    "sales.receipt.paid": "Paid",
    "sales.receipt.debt": "Debt",
    "sales.receipt.status": "Status",
    "customers.title": "Customers",
    "customers.search": "Search customers...",
    "customers.add": "Add customer",
    "customers.actions.deleteAll": "Delete all customers",
    "customers.form.name": "Name",
    "customers.form.phone": "Phone",
    "customers.form.notes": "Notes",
    "customers.form.save": "Save",
    "customers.empty": "No customers found",
    "customers.totalSpent": "Total spent",
    "customers.totalPaid": "Total paid",
    "customers.totalDebt": "Total debt",
    "customers.transactions": "Transactions",
    "customers.noTransactions": "No transactions yet",
    "customers.totalTransactions": "Total transactions",
    "customers.dialog.edit": "Edit customer",
    "customers.dialog.add": "Add customer",
    "customers.export.all": "Export all",
    "customers.export.single": "Export report",
    "customers.export.overviewFilename": "customers_overview",
    "customers.export.overviewSheet": "Customers",
    "customers.export.summarySheet": "Summary",
    "customers.export.transactionsSheet": "Transactions",
    "customers.export.reportSuffix": "report",
    "customers.export.columns.customerId": "Customer ID",
    "customers.export.columns.customerName": "Customer Name",
    "customers.export.columns.customer": "Customer",
    "customers.export.columns.phone": "Phone",
    "customers.export.columns.notes": "Notes",
    "customers.export.columns.totalTransactions": "Total Transactions",
    "customers.export.columns.totalSpent": "Total Spent",
    "customers.export.columns.fullyPaid": "Fully Paid",
    "customers.export.columns.outstandingDebt": "Outstanding Debt",
    "customers.export.columns.transactionId": "Transaction ID",
    "customers.export.columns.date": "Date",
    "customers.export.columns.status": "Payment Status",
    "customers.export.columns.transactionTotal": "Transaction Total",
    "customers.export.columns.item": "Item",
    "customers.export.columns.quantity": "Quantity",
    "customers.export.columns.unitPrice": "Unit Price",
    "customers.export.columns.lineTotal": "Line Total",
    "customers.status.debt": "Debt",
    "customers.status.paid": "Fully Paid",
    "customers.toast.updated": "Customer updated successfully",
    "customers.toast.added": "Customer added successfully",
    "customers.toast.saveError": "Failed to save customer",
    "customers.toast.statusUpdated": "Payment status updated",
    "customers.toast.amountUpdated": "Payment updated",
    "customers.toast.invalidAmount": "Please enter a valid amount",
    "customers.toast.statusError": "Failed to update payment status",
    "customers.toast.deleted": "Customer removed",
    "customers.toast.allDeleted": "All customers removed",
    "customers.toast.noCustomersToDelete": "There are no customers to delete.",
    "customers.toast.noExport": "No customers available to export",
    "customers.confirm.delete": "Delete customer \"{name}\"? This will remove their transactions.",
    "customers.confirm.deleteAll": "Delete all customers and their transactions? This cannot be undone.",
    "customers.transactions.hide": "Hide transactions",
    "shopping.title": "Shopping Lists",
    "shopping.stats.active": "Active lists",
    "shopping.stats.pending": "Pending items",
    "shopping.stats.outstanding": "Outstanding budget",
    "shopping.monthly.subtitle": "Monthly restock list",
    "shopping.monthly.pending": "Pending items: {count}",
    "shopping.monthly.view": "Open list",
    "shopping.monthly.transfer": "Transfer items",
    "shopping.monthly.helper": "Sales automatically add sold quantities back here for the next restock.",
    "shopping.intro.heading": "Shopping lists",
    "shopping.intro.description": "Create dedicated pages for each procurement plan and keep them easy to find.",
    "shopping.actions.newList": "New list",
    "shopping.dialog.editTitle": "Edit shopping list",
    "shopping.dialog.createTitle": "Create shopping list",
    "shopping.dialog.description": "Group purchases for depot restock or special customer orders.",
    "shopping.form.title": "Title",
    "shopping.form.type": "Type",
    "shopping.form.typePlaceholder": "Choose type",
    "shopping.form.status": "Status",
    "shopping.form.statusPlaceholder": "Select status",
    "shopping.form.priority": "Priority",
    "shopping.form.priorityPlaceholder": "Select priority",
    "shopping.form.expectedDate": "Expected date",
    "shopping.form.customer": "Customer",
    "shopping.form.customerPlaceholder": "Select customer",
    "shopping.form.customerUnassigned": "Unassigned",
    "shopping.form.notes": "Notes",
    "shopping.form.notesPlaceholder": "Extra details, supplier info, delivery reminders...",
    "shopping.form.submit.save": "Save changes",
    "shopping.form.submit.create": "Create list",
    "shopping.form.validation.title": "List title is required",
    "shopping.search.label": "Search",
    "shopping.search.placeholder": "Search by title or customer",
    "shopping.filter.label": "Filter",
    "shopping.filter.placeholder": "Filter lists",
    "shopping.filter.all": "All lists",
    "shopping.filter.restock": "Depot restock",
    "shopping.filter.customer": "Customer orders",
    "shopping.filter.completed": "Completed",
    "shopping.empty": "No lists match your filters. Adjust the search to see more results.",
    "shopping.type.restock": "Depot restock",
    "shopping.type.customerOrder": "Customer order",
    "shopping.type.monthlyRestock": "Monthly restock",
    "shopping.status.active": "Active",
    "shopping.status.completed": "Completed",
    "shopping.status.archived": "Archived",
    "shopping.priority.high": "High",
    "shopping.priority.medium": "Medium",
    "shopping.priority.low": "Low",
    "shopping.priority.badge": "{priority} priority",
    "shopping.list.customerLabel": "Customer: {name}",
    "shopping.list.due": "Due {date}",
    "shopping.list.summary.items": "{count} items",
    "shopping.list.summary.pending": "{count} pending",
    "shopping.list.summary.budget": "Budget: {amount}",
    "shopping.list.viewDetails": "View details",
    "shopping.actions.edit": "Edit",
    "shopping.actions.reopen": "Reopen list",
    "shopping.actions.markCompleted": "Mark as completed",
    "shopping.actions.delete": "Delete",
    "shopping.actions.deleteAll": "Delete all lists",
    "shopping.actions.deleteList": "Delete list",
    "shopping.actions.export": "Export",
    "shopping.actions.back": "Back to shopping lists",
    "shopping.toast.listUpdated": "Shopping list updated",
    "shopping.toast.listCreated": "Shopping list created",
    "shopping.toast.listSaveError": "Failed to save shopping list",
    "shopping.toast.listDeleted": "Shopping list removed",
    "shopping.toast.listCompleted": "List marked as completed",
    "shopping.toast.itemsTransferred": "Updated {count} depot products",
    "shopping.toast.listReopened": "List reopened",
    "shopping.toast.allDeleted": "All shopping lists removed",
    "shopping.toast.noListsToDelete": "There are no shopping lists to delete.",
    "shopping.confirm.deleteList": "Delete the shopping list \"{title}\" and all of its items?",
    "shopping.confirm.deleteAll": "Delete all shopping lists and their items? This cannot be undone.",
    "shopping.detail.title": "Shopping List",
    "shopping.detail.invalidUrl": "Invalid shopping list URL.",
    "shopping.detail.notFound": "This shopping list could not be found.",
    "shopping.detail.actions.manage": "Manage list",
    "shopping.detail.actions.editDetails": "Edit details",
    "shopping.detail.toast.listMissing": "Shopping list not found",
    "shopping.detail.toast.itemNameRequired": "Item name is required",
    "shopping.detail.toast.itemUpdated": "Shopping list item updated",
    "shopping.detail.toast.itemCreated": "Item added to shopping list",
    "shopping.detail.toast.itemSaveError": "Failed to save item",
    "shopping.detail.toast.itemDeleted": "Item removed",
    "shopping.detail.toast.listSaveError": "Failed to update shopping list",
    "shopping.detail.confirm.deleteItem": "Delete \"{name}\" from this shopping list?",
    "shopping.itemStatus.completed": "Completed",
    "shopping.itemStatus.pending": "Pending",
    "shopping.detail.stats.totalEstimated": "Total estimated",
    "shopping.detail.stats.pendingBudget": "Pending budget",
    "shopping.detail.stats.progress": "Progress",
    "shopping.detail.stats.pendingItems": "Pending items",
    "shopping.detail.stats.completedItems": "Completed items",
    "shopping.detail.stats.created": "Created",
    "shopping.detail.sections.items": "Items",
    "shopping.detail.dialog.addItem": "Add item",
    "shopping.detail.dialog.editItem": "Edit item",
    "shopping.detail.dialog.itemDescription": "Link to depot products or create quick shopping notes.",
    "shopping.detail.form.depotProduct": "Depot product",
    "shopping.detail.form.productPlaceholder": "Choose a product",
    "shopping.detail.form.customItem": "Custom item",
    "shopping.detail.form.name": "Name",
    "shopping.detail.form.quantity": "Quantity",
    "shopping.detail.form.unit": "Unit",
    "shopping.detail.form.estimatedUnitCost": "Estimated unit cost",
    "shopping.detail.form.notesPlaceholder": "Supplier hints, variants, delivery reminders...",
    "shopping.detail.form.submit.add": "Add item",
    "shopping.detail.form.submit.save": "Save changes",
    "shopping.detail.pending.title": "Pending items",
    "shopping.detail.pending.empty": "All set! Add new items to keep the procurement queue filled.",
    "shopping.detail.items.linkedToDepot": "Linked to depot",
    "shopping.detail.items.quantityPrefix": "Qty:",
    "shopping.detail.items.productInfo": "Stock: {stock} • Buy price: {price}",
    "shopping.detail.items.costSummary": "Unit cost: {unitCost} • Estimated total: {total}",
    "shopping.detail.items.addedOn": "Added on {date}",
    "shopping.detail.items.finalCost": "Final cost: {total}",
    "shopping.detail.items.completedOn": "Completed on {date}",
    "shopping.detail.completed.title": "Completed",
    "shopping.detail.completed.empty": "Completed items will appear here once you mark them as done.",
    "shopping.detail.dialog.listTitle": "Edit shopping list",
    "shopping.detail.dialog.listDescription": "Update details for this shopping list.",
    "shopping.detail.export.summarySheet": "Summary",
    "shopping.detail.export.itemsSheet": "Items",
    "shopping.detail.export.columns.listName": "List name",
    "shopping.detail.export.columns.type": "Type",
    "shopping.detail.export.columns.status": "Status",
    "shopping.detail.export.columns.priority": "Priority",
    "shopping.detail.export.columns.totalItems": "Total items",
    "shopping.detail.export.columns.pendingItems": "Pending items",
    "shopping.detail.export.columns.completedItems": "Completed items",
    "shopping.detail.export.columns.estimatedTotal": "Estimated total",
    "shopping.detail.export.columns.pendingBudget": "Pending budget",
    "shopping.detail.export.columns.customer": "Customer",
    "shopping.detail.export.columns.dueDate": "Due date",
    "shopping.detail.export.columns.notes": "Notes",
    "shopping.detail.export.columns.itemName": "Name",
    "shopping.detail.export.columns.itemQuantity": "Quantity",
    "shopping.detail.export.columns.itemUnit": "Unit",
    "shopping.detail.export.columns.itemUnitCost": "Unit cost",
    "shopping.detail.export.columns.itemEstimatedTotal": "Estimated total",
    "shopping.detail.export.columns.itemLinkedProduct": "Linked product",
    "shopping.detail.export.columns.itemStatus": "Status",
    "shopping.detail.export.columns.created": "Created",
    "customers.transactions.view": "View transactions",
    "customers.transactions.transactionNumber": "Transaction #{id}",
    "customers.transactions.setStatus": "Set status to {status}",
    "customers.transactions.adjustAmount": "Adjust amount",
    "customers.transactions.adjustPrompt": "Enter amount to pay (outstanding {amount})",
    "customers.transactions.outstanding": "Outstanding: {amount}",
    "customers.transactions.itemsCount": "{count} item(s)",
    "customers.transactions.itemSummary": "{name} • {quantity} × {price}",
    "customers.noMatches": "No customers match your search.",
    "history.title": "History",
    "history.search": "Search transactions...",
    "history.export.all": "Export all",
    "history.export.summary": "Export summary",
    "history.export.filename": "transactions_history",
    "history.export.summarySheet": "Summary",
    "history.export.transactionsSheet": "Transactions",
    "history.toast.noExport": "No transactions to export",
    "history.toast.invalidPeriod": "Select a valid period to export",
    "history.toast.noPeriodTransactions": "No transactions in the selected period",
    "history.toast.summaryExported": "Summary exported successfully",
    "history.summary.title": "Export summary",
    "history.summary.description": "Choose a period to export a snapshot of sales activity.",
    "history.summary.periodLabel": "Summary period",
    "history.summary.periodPlaceholder": "Select period",
    "history.summary.period.day": "Day",
    "history.summary.period.week": "Week",
    "history.summary.period.month": "Month",
    "history.summary.period.year": "Year",
    "history.summary.dayLabel": "Select day",
    "history.summary.weekLabel": "Select week",
    "history.summary.monthLabel": "Select month",
    "history.summary.yearLabel": "Select year",
    "history.summary.period": "Summary Period",
    "history.summary.start": "Start",
    "history.summary.end": "End",
    "history.summary.totalAmount": "Total Amount",
    "history.summary.preview": "Range",
    "history.summary.previewInvalid": "Select a valid period",
    "history.summary.table.date": "Date & Time",
    "history.summary.table.saleType": "Sale Type",
    "history.summary.table.items": "Items",
    "history.export.filenamePrompt": "Choose file name",
    "history.export.logSheet": "Log",
    "history.log.saleDebt": "Sale (Debt)",
    "history.log.salePaid": "Sale (Paid)",
    "history.log.payment": "Payment",
    "history.log.adjustment": "Adjustment",
    "history.log.paymentNote": "Payment for transaction #{id}",
    "history.log.columns.time": "Time",
    "history.log.columns.customer": "Customer",
    "history.log.columns.type": "Type",
    "history.log.columns.total": "Total",
    "history.log.columns.items": "Items / Note",
    "history.transactionNumber": "Transaction #{id}",
    "history.transactionItemsCount": "{count} item(s)",
    "history.detail.customer": "Customer",
    "history.detail.status": "Status",
    "history.detail.itemsTitle": "Items",
    "history.detail.itemsSubtotal": "Items subtotal",
    "history.detail.noItems": "No items recorded for this transaction.",
    "history.noMatches": "No transactions match your search.",
    "history.filter.all": "All",
    "history.filter.paid": "Fully paid",
    "history.filter.debt": "Debt",
    "history.empty": "No transactions recorded",
    "history.receipt": "View receipt",
    "notFound.title": "Page not found",
    "notFound.message": "The page you are looking for does not exist.",
    "notFound.back": "Go back home",
    "settings.title": "Settings & Data",
    "settings.backup.title": "Database Backup",
    "settings.backup.description": "Export and import your data",
    "settings.backup.filenamePrompt": "Choose a file name",
    "settings.backup.export": "Export Database as JSON",
    "settings.backup.import": "Import Database from JSON",
    "settings.backup.note": "All data is stored locally in your browser. Use export to create backups and import to restore data on another device.",
    "settings.auth.title": "Authentication",
    "settings.auth.description": "Manage your current session.",
    "settings.auth.signedInAs": "Signed in as {user}",
    "settings.auth.signOut": "Sign out",
    "settings.auth.unknownUser": "unknown user",
    "settings.about.title": "About",
    "settings.about.app": "App",
    "settings.about.version": "Version",
    "settings.about.storage": "Storage",
    "settings.toast.exportSuccess": "Database exported successfully",
    "settings.toast.exportError": "Failed to export database",
    "settings.toast.importSuccess": "Database imported successfully. Reloading...",
    "settings.toast.importError": "Failed to import database",
    "settings.toast.readError": "Failed to read file",
    "toast.genericError": "Something went wrong",
  },
  tr: {
    "common.cancel": "İptal",
    "app.name": "Çevrimdışı Stok Uygulaması",
    "app.tagline": "Yerel mağazalar için envanter ve satış yönetimi",
    "app.initializing": "Veritabanı hazırlanıyor...",
    "nav.depot": "Depo",
    "nav.sales": "Satış",
    "nav.customers": "Müşteriler",
    "nav.shopping": "Alışveriş",
    "nav.history": "Geçmiş",
    "nav.settings": "Ayarlar",
    "layout.theme": "Tema",
    "layout.language": "Dil",
    "layout.defaultTitle": "Magazin Proekt",
    "theme.light": "Açık",
    "theme.dark": "Koyu",
    "theme.system": "Sistem",
    "language.english": "English",
    "language.turkish": "Türkçe",
    "language.russian": "Русский",
    "login.title": "Çevrimdışı Stok Uygulaması",
    "login.subtitle": "Devam etmek için rumuzunuz ve şifrenizle giriş yapın.",
    "login.nickname": "Rumuz",
    "login.nickname.placeholder": "Rumuzunuzu girin",
    "login.password": "Şifre",
    "login.password.placeholder": "Şifrenizi girin",
    "login.remember": "Bu cihazda beni hatırla",
    "login.submit": "Giriş yap",
    "login.submitting": "Giriş yapılıyor...",
    "login.signup.question": "Hesabınız yok mu?",
    "login.signup.link": "Kayıt ol",
    "login.validation": "Rumuz ve şifre zorunludur",
    "signup.title": "Hesap oluştur",
    "signup.subtitle": "Mağazayı güvene almak için yönetici bilgilerini ayarlayın.",
    "signup.nickname": "Rumuz",
    "signup.nickname.placeholder": "Bir rumuz seçin",
    "signup.password": "Şifre",
    "signup.password.placeholder": "Bir şifre seçin",
    "signup.confirmPassword": "Şifreyi onayla",
    "signup.confirmPassword.placeholder": "Şifreyi tekrar girin",
    "signup.submit": "Hesap oluştur",
    "signup.submitting": "Hesap oluşturuluyor...",
    "signup.haveAccount": "Zaten hesabınız var mı?",
    "signup.login": "Giriş yap",
    "signup.passwordMismatch": "Şifreler uyuşmuyor",
    "signup.validation": "Rumuz ve şifre zorunludur",
    "signup.passwordLength": "Şifre en az 6 karakter olmalıdır",
    "depot.title": "Magazin Proekt",
    "depot.search.placeholder": "Ürünlerde ara...",
    "depot.add": "Ekle",
    "depot.addProduct": "Ürün ekle",
    "depot.editProduct": "Ürünü düzenle",
    "depot.form.name": "Ad",
    "depot.form.barcode": "Barkod/SKU",
    "depot.form.category": "Kategori",
    "depot.form.buyPrice": "Alış fiyatı",
    "depot.form.sellPrice": "Satış fiyatı",
    "depot.form.quantity": "Miktar",
    "depot.form.minStock": "Min stok",
    "depot.form.save": "Kaydet",
    "depot.export": "Dışa aktar",
    "depot.export.filename": "envanter",
    "depot.export.sheetName": "Ürünler",
    "depot.filter.all": "Tümü",
    "depot.filter.category": "Kategori",
    "depot.filter.searchPlaceholder": "Kategorilerde ara...",
    "depot.filter.noResults": "Kategori bulunamadı",
    "depot.filter.uncategorized": "Kategorisiz",
    "depot.actions.deleteAll": "Tüm ürünleri sil",
    "depot.badge.low": "Az",
    "depot.price.buy": "Alış:",
    "depot.price.sell": "Satış:",
    "depot.totals.buy": "Toplam alış",
    "depot.totals.sell": "Toplam satış",
    "depot.totals.monthSelector": "Satış ayı",
    "depot.totals.clearMonth": "Tümünü göster",
    "depot.totals.monthlySales": "Aylık satış",
    "depot.stock": "stokta",
    "depot.empty": "Ürün bulunamadı",
    "depot.toast.added": "Ürün başarıyla eklendi",
    "depot.toast.updated": "Ürün başarıyla güncellendi",
    "depot.toast.savedError": "Ürün kaydedilemedi",
    "depot.toast.increased": "Stok artırıldı",
    "depot.toast.decreased": "Stok azaltıldı",
    "depot.toast.deleted": "Ürün silindi",
    "depot.toast.allDeleted": "Tüm ürünler silindi",
    "depot.toast.noProductsToDelete": "Silinecek ürün yok.",
    "depot.toast.noExport": "Dışa aktarılacak ürün yok",
    "depot.confirm.delete": "\"{name}\" ürününü depodan silmek istiyor musunuz?",
    "depot.confirm.deleteAll": "Tüm ürünler silinsin ve alışveriş listelerinden kaldırılsın mı? Bu işlem geri alınamaz.",
    "depot.export.name": "Ad",
    "depot.export.barcode": "Barkod",
    "depot.export.category": "Kategori",
    "depot.export.buyPrice": "Alış fiyatı",
    "depot.export.sellPrice": "Satış fiyatı",
    "depot.export.quantity": "Miktar",
    "depot.export.minStock": "Minimum stok",
    "sales.title": "Satış",
    "sales.searchProducts": "Ürünlerde ara...",
    "sales.openCatalog": "Ürün ekle",
    "sales.cartSearch": "Sepette ara...",
    "sales.cart": "Sepet",
    "sales.noItems": "Sepette ürün yok",
    "sales.totals": "Toplamlar",
    "sales.total": "Toplam",
    "sales.paid": "Ödenen",
    "sales.debt": "Borç",
    "sales.saleType": "Satış türü",
    "sales.saleType.paid": "Peşin",
    "sales.saleType.debt": "Borç",
    "sales.customer": "Müşteri",
    "sales.customer.select": "Müşteri seç",
    "sales.customer.new": "Yeni müşteri ekle",
    "sales.customer.none": "Müşteri bulunamadı",
    "sales.newCustomer.title": "Yeni müşteri",
    "sales.newCustomer.name": "Ad",
    "sales.newCustomer.phone": "Telefon",
    "sales.newCustomer.notes": "Notlar",
    "sales.newCustomer.submit": "Oluştur",
    "sales.newCustomer.cancel": "Vazgeç",
    "sales.complete": "Satışı tamamla",
    "sales.clear": "Sepeti temizle",
    "sales.toast.noStock": "Yeterli stok yok",
    "sales.toast.added": "Sepete eklendi",
    "sales.toast.nameRequired": "Müşteri adı gerekli",
    "sales.toast.created": "Müşteri başarıyla oluşturuldu",
    "sales.toast.createError": "Müşteri oluşturulamadı",
    "sales.toast.empty": "Sepet boş",
    "sales.toast.customerRequired": "Borç satış için müşteri seçin",
    "sales.toast.failed": "Satış tamamlanamadı",
    "sales.toast.completed": "Satış kaydedildi",
    "sales.debtNote": "Borç satışları için müşteri seçilmelidir ve tamamen ödenene kadar takip edilir.",
    "sales.customerTotal": "{name} için toplam",
    "sales.unitPrice": "Birim fiyat: {price}",
    "sales.priceLabel": "Fiyat",
    "sales.noMatches": "Sepette aramanıza uyan ürün yok.",
    "sales.receipt.title": "Satış fişi",
    "sales.receipt.customer": "Müşteri",
    "sales.receipt.date": "Tarih",
    "sales.receipt.cashier": "Kasiyer",
    "sales.receipt.items": "Ürünler",
    "sales.receipt.total": "Toplam",
    "sales.receipt.paid": "Ödenен",
    "sales.receipt.debt": "Borç",
    "sales.receipt.status": "Durum",
    "customers.title": "Müşteriler",
    "customers.search": "Müşteri ara...",
    "customers.add": "Müşteri ekle",
    "customers.actions.deleteAll": "Tüm müşterileri sil",
    "customers.form.name": "Ad",
    "customers.form.phone": "Telefon",
    "customers.form.notes": "Notlar",
    "customers.form.save": "Kaydet",
    "customers.empty": "Müşteri bulunamadı",
    "customers.totalSpent": "Toplam harcama",
    "customers.totalPaid": "Toplam ödeme",
    "customers.totalDebt": "Toplam borç",
    "customers.transactions": "İşlemler",
    "customers.noTransactions": "Henüz işlem yok",
    "customers.totalTransactions": "Toplam işlem",
    "customers.dialog.edit": "Müşteriyi düzenle",
    "customers.dialog.add": "Müşteri ekle",
    "customers.export.all": "Tümünü dışa aktar",
    "customers.export.single": "Raporu dışa aktar",
    "customers.export.overviewFilename": "customers_overview",
    "customers.export.overviewSheet": "Müşteriler",
    "customers.export.summarySheet": "Özet",
    "customers.export.transactionsSheet": "İşlemler",
    "customers.export.reportSuffix": "rapor",
    "customers.export.columns.customerId": "Müşteri ID",
    "customers.export.columns.customerName": "Müşteri adı",
    "customers.export.columns.customer": "Müşteri",
    "customers.export.columns.phone": "Telefon",
    "customers.export.columns.notes": "Notlar",
    "customers.export.columns.totalTransactions": "Toplam işlem",
    "customers.export.columns.totalSpent": "Toplam harcama",
    "customers.export.columns.fullyPaid": "Tam ödendi",
    "customers.export.columns.outstandingDebt": "Açık borç",
    "customers.export.columns.transactionId": "İşlem ID",
    "customers.export.columns.date": "Tarih",
    "customers.export.columns.status": "Ödeme durumu",
    "customers.export.columns.transactionTotal": "İşlem toplamı",
    "customers.export.columns.item": "Ürün",
    "customers.export.columns.quantity": "Miktar",
    "customers.export.columns.unitPrice": "Birim fiyat",
    "customers.export.columns.lineTotal": "Ara toplam",
    "customers.status.debt": "Borç",
    "customers.status.paid": "Tam ödendi",
    "customers.toast.updated": "Müşteri güncellendi",
    "customers.toast.added": "Müşteri eklendi",
    "customers.toast.saveError": "Müşteri kaydedilemedi",
    "customers.toast.statusUpdated": "Ödeme durumu güncellendi",
    "customers.toast.amountUpdated": "Ödeme güncellendi",
    "customers.toast.invalidAmount": "Geçerli bir tutar girin",
    "customers.toast.statusError": "Ödeme durumu güncellenemedi",
    "customers.toast.deleted": "Müşteri silindi",
    "customers.toast.allDeleted": "Tüm müşteriler silindi",
    "customers.toast.noCustomersToDelete": "Silinecek müşteri yok.",
    "customers.toast.noExport": "Dışa aktarılacak müşteri yok",
    "customers.confirm.delete": "\"{name}\" müşterisi silinsin mi? Bu işlem tüm işlemlerini kaldırır.",
    "customers.confirm.deleteAll": "Tüm müşteriler ve işlemleri silinsin mi? Bu işlem geri alınamaz.",
    "customers.transactions.hide": "İşlemleri gizle",
    "shopping.title": "Alışveriş Listeleri",
    "shopping.stats.active": "Aktif listeler",
    "shopping.stats.pending": "Bekleyen kalemler",
    "shopping.stats.outstanding": "Bekleyen bütçe",
    "shopping.monthly.subtitle": "Aylık stok listesi",
    "shopping.monthly.pending": "Bekleyen ürün: {count}",
    "shopping.monthly.view": "Listeyi aç",
    "shopping.monthly.transfer": "Ürünleri aktar",
    "shopping.monthly.helper": "Satışlar, bir sonraki tedarik için satılan miktarları buraya ekler.",
    "shopping.intro.heading": "Alışveriş listeleri",
    "shopping.intro.description": "Her tedarik planı için ayrı sayfalar oluşturun ve kolayca erişin.",
    "shopping.actions.newList": "Yeni liste",
    "shopping.actions.deleteAll": "Tüm listeleri sil",
    "shopping.dialog.editTitle": "Alışveriş listesini düzenle",
    "shopping.dialog.createTitle": "Alışveriş listesi oluştur",
    "shopping.dialog.description": "Depo takviyesi veya özel müşteri siparişleri için alımları gruplayın.",
    "shopping.form.title": "Başlık",
    "shopping.form.type": "Tür",
    "shopping.form.typePlaceholder": "Tür seçin",
    "shopping.form.status": "Durum",
    "shopping.form.statusPlaceholder": "Durum seçin",
    "shopping.form.priority": "Öncelik",
    "shopping.form.priorityPlaceholder": "Öncelik seçin",
    "shopping.form.expectedDate": "Beklenen tarih",
    "shopping.form.customer": "Müşteri",
    "shopping.form.customerPlaceholder": "Müşteri seçin",
    "shopping.form.customerUnassigned": "Atanmadı",
    "shopping.form.notes": "Notlar",
    "shopping.form.notesPlaceholder": "Ek detaylar, tedarikçi bilgileri, teslimat hatırlatmaları...",
    "shopping.form.submit.save": "Değişiklikleri kaydet",
    "shopping.form.submit.create": "Liste oluştur",
    "shopping.form.validation.title": "Liste başlığı zorunludur",
    "shopping.search.label": "Ara",
    "shopping.search.placeholder": "Başlığa veya müşteriye göre arayın",
    "shopping.filter.label": "Filtre",
    "shopping.filter.placeholder": "Listeleri filtrele",
    "shopping.filter.all": "Tüm listeler",
    "shopping.filter.restock": "Depo stoğu",
    "shopping.filter.customer": "Müşteri siparişleri",
    "shopping.filter.completed": "Tamamlanan",
    "shopping.empty": "Filtrelerinize uyan liste yok. Daha fazla sonuç için aramayı değiştirin.",
    "shopping.type.restock": "Depo stoğu",
    "shopping.type.customerOrder": "Müşteri siparişi",
    "shopping.type.monthlyRestock": "Aylık stok listesi",
    "shopping.status.active": "Aktif",
    "shopping.status.completed": "Tamamlandı",
    "shopping.status.archived": "Arşivlendi",
    "shopping.priority.high": "Yüksek",
    "shopping.priority.medium": "Orta",
    "shopping.priority.low": "Düşük",
    "shopping.priority.badge": "{priority} öncelik",
    "shopping.list.customerLabel": "Müşteri: {name}",
    "shopping.list.due": "Son tarih {date}",
    "shopping.list.summary.items": "{count} kalem",
    "shopping.list.summary.pending": "{count} bekliyor",
    "shopping.list.summary.budget": "Bütçe: {amount}",
    "shopping.list.viewDetails": "Detayları görüntüle",
    "shopping.actions.edit": "Düzenle",
    "shopping.actions.reopen": "Listeyi yeniden aç",
    "shopping.actions.markCompleted": "Listeyi tamamlandı işaretle",
    "shopping.actions.delete": "Sil",
    "shopping.actions.deleteList": "Listeyi sil",
    "shopping.actions.export": "Dışa aktar",
    "shopping.actions.back": "Alışveriş listelerine dön",
    "shopping.toast.listUpdated": "Alışveriş listesi güncellendi",
    "shopping.toast.listCreated": "Alışveriş listesi oluşturuldu",
    "shopping.toast.listSaveError": "Alışveriş listesi kaydedilemedi",
    "shopping.toast.listDeleted": "Alışveriş listesi kaldırıldı",
    "shopping.toast.listCompleted": "Liste tamamlandı olarak işaretlendi",
    "shopping.toast.itemsTransferred": "Depoda {count} ürün güncellendi",
    "shopping.toast.listReopened": "Liste yeniden açıldı",
    "shopping.toast.allDeleted": "Tüm alışveriş listeleri silindi",
    "shopping.toast.noListsToDelete": "Silinecek alışveriş listesi yok.",
    "shopping.confirm.deleteList": "\"{title}\" alışveriş listesi ve tüm kalemleri silinsin mi?",
    "shopping.confirm.deleteAll": "Tüm alışveriş listeleri ve öğeleri silinsin mi? Bu işlem geri alınamaz.",
    "shopping.detail.title": "Alışveriş Listesi",
    "shopping.detail.invalidUrl": "Geçersiz alışveriş listesi URL'si.",
    "shopping.detail.notFound": "Bu alışveriş listesi bulunamadı.",
    "shopping.detail.actions.manage": "Listeyi yönet",
    "shopping.detail.actions.editDetails": "Detayları düzenle",
    "shopping.detail.toast.listMissing": "Alışveriş listesi bulunamadı",
    "shopping.detail.toast.itemNameRequired": "Kalem adı zorunludur",
    "shopping.detail.toast.itemUpdated": "Alışveriş listesi kalemi güncellendi",
    "shopping.detail.toast.itemCreated": "Kalem alışveriş listesine eklendi",
    "shopping.detail.toast.itemSaveError": "Kalem kaydedilemedi",
    "shopping.detail.toast.itemDeleted": "Kalem kaldırıldı",
    "shopping.detail.toast.listSaveError": "Alışveriş listesi güncellenemedi",
    "shopping.detail.confirm.deleteItem": "\"{name}\" bu alışveriş listesinden silinsin mi?",
    "shopping.itemStatus.completed": "Tamamlandı",
    "shopping.itemStatus.pending": "Beklemede",
    "shopping.detail.stats.totalEstimated": "Tahmini toplam",
    "shopping.detail.stats.pendingBudget": "Bekleyen bütçe",
    "shopping.detail.stats.progress": "İlerleme",
    "shopping.detail.stats.pendingItems": "Bekleyen kalem",
    "shopping.detail.stats.completedItems": "Tamamlanan kalem",
    "shopping.detail.stats.created": "Oluşturulma",
    "shopping.detail.sections.items": "Kalemler",
    "shopping.detail.dialog.addItem": "Kalem ekle",
    "shopping.detail.dialog.editItem": "Kalemi düzenle",
    "shopping.detail.dialog.itemDescription": "Depo ürünlerine bağlayın veya hızlı alışveriş notları oluşturun.",
    "shopping.detail.form.depotProduct": "Depo ürünü",
    "shopping.detail.form.productPlaceholder": "Ürün seçin",
    "shopping.detail.form.customItem": "Özel kalem",
    "shopping.detail.form.name": "Ad",
    "shopping.detail.form.quantity": "Miktar",
    "shopping.detail.form.unit": "Birim",
    "shopping.detail.form.estimatedUnitCost": "Tahmini birim maliyet",
    "shopping.detail.form.notesPlaceholder": "Tedarikçi ipuçları, varyantlar, teslimat hatırlatmaları...",
    "shopping.detail.form.submit.add": "Kalem ekle",
    "shopping.detail.form.submit.save": "Değişiklikleri kaydet",
    "shopping.detail.pending.title": "Bekleyen kalemler",
    "shopping.detail.pending.empty": "Her şey hazır! Satın alma kuyruğunu doldurmak için yeni kalemler ekleyin.",
    "shopping.detail.items.linkedToDepot": "Depoya bağlı",
    "shopping.detail.items.quantityPrefix": "Adet:",
    "shopping.detail.items.productInfo": "Stok: {stock} • Alış fiyatı: {price}",
    "shopping.detail.items.costSummary": "Birim maliyet: {unitCost} • Tahmini toplam: {total}",
    "shopping.detail.items.addedOn": "{date} tarihinde eklendi",
    "shopping.detail.items.finalCost": "Nihai tutar: {total}",
    "shopping.detail.items.completedOn": "{date} tarihinde tamamlandı",
    "shopping.detail.completed.title": "Tamamlanan",
    "shopping.detail.completed.empty": "Kalemleri tamamlandı olarak işaretlediğinizde burada görünecek.",
    "shopping.detail.dialog.listTitle": "Alışveriş listesini düzenle",
    "shopping.detail.dialog.listDescription": "Bu alışveriş listesinin detaylarını güncelleyin.",
    "shopping.detail.export.summarySheet": "Özet",
    "shopping.detail.export.itemsSheet": "Kalemler",
    "shopping.detail.export.columns.listName": "Liste adı",
    "shopping.detail.export.columns.type": "Tür",
    "shopping.detail.export.columns.status": "Durum",
    "shopping.detail.export.columns.priority": "Öncelik",
    "shopping.detail.export.columns.totalItems": "Toplam kalem",
    "shopping.detail.export.columns.pendingItems": "Bekleyen kalem",
    "shopping.detail.export.columns.completedItems": "Tamamlanan kalem",
    "shopping.detail.export.columns.estimatedTotal": "Tahmini toplam",
    "shopping.detail.export.columns.pendingBudget": "Bekleyen bütçe",
    "shopping.detail.export.columns.customer": "Müşteri",
    "shopping.detail.export.columns.dueDate": "Teslim tarihi",
    "shopping.detail.export.columns.notes": "Notlar",
    "shopping.detail.export.columns.itemName": "Ad",
    "shopping.detail.export.columns.itemQuantity": "Miktar",
    "shopping.detail.export.columns.itemUnit": "Birim",
    "shopping.detail.export.columns.itemUnitCost": "Birim maliyet",
    "shopping.detail.export.columns.itemEstimatedTotal": "Tahmini toplam",
    "shopping.detail.export.columns.itemLinkedProduct": "Bağlı ürün",
    "shopping.detail.export.columns.itemStatus": "Durum",
    "shopping.detail.export.columns.created": "Oluşturuldu",
    "customers.transactions.view": "İşlemleri görüntüle",
    "customers.transactions.transactionNumber": "İşlem #{id}",
    "customers.transactions.setStatus": "Durumu {status} yap",
    "customers.transactions.adjustAmount": "Tutarı güncelle",
    "customers.transactions.adjustPrompt": "Ödenecek tutarı girin (kalan {amount})",
    "customers.transactions.outstanding": "Kalan: {amount}",
    "customers.transactions.itemsCount": "{count} öğe",
    "customers.transactions.itemSummary": "{name} • {quantity} × {price}",
    "customers.noMatches": "Aramanızla eşleşen müşteri yok.",
    "history.title": "Geçmiş",
    "history.search": "İşlem ara...",
    "history.export.all": "Tümünü dışa aktar",
    "history.export.summary": "Özeti dışa aktar",
    "history.export.filename": "islem_gecmisi",
    "history.export.summarySheet": "Özet",
    "history.export.transactionsSheet": "İşlemler",
    "history.toast.noExport": "Dışa aktarılacak işlem yok",
    "history.toast.invalidPeriod": "Geçerli bir dönem seçin",
    "history.toast.noPeriodTransactions": "Seçilen dönemde işlem yok",
    "history.toast.summaryExported": "Özet başarıyla dışa aktarıldı",
    "history.summary.title": "Özeti dışa aktar",
    "history.summary.description": "Satış faaliyetlerinin özetini dışa aktarmak için bir dönem seçin.",
    "history.summary.periodLabel": "Özet dönemi",
    "history.summary.periodPlaceholder": "Dönem seçin",
    "history.summary.period.day": "Gün",
    "history.summary.period.week": "Hafta",
    "history.summary.period.month": "Ay",
    "history.summary.period.year": "Yıl",
    "history.summary.dayLabel": "Gün seç",
    "history.summary.weekLabel": "Hafta seç",
    "history.summary.monthLabel": "Ay seç",
    "history.summary.yearLabel": "Yıl seç",
    "history.summary.period": "Özet dönemi",
    "history.summary.start": "Başlangıç",
    "history.summary.end": "Bitiş",
    "history.summary.totalAmount": "Toplam tutar",
    "history.summary.preview": "Aralık",
    "history.summary.previewInvalid": "Geçerli bir dönem seçin",
    "history.export.filenamePrompt": "Dosya adı seçin",
    "history.export.logSheet": "Günlük",
    "history.log.saleDebt": "Satış (Borç)",
    "history.log.salePaid": "Satış (Ödendi)",
    "history.log.payment": "Ödeme",
    "history.log.adjustment": "Düzeltme",
    "history.log.paymentNote": "{id} nolu işlem için ödeme",
    "history.log.columns.time": "Zaman",
    "history.log.columns.customer": "Müşteri",
    "history.log.columns.type": "Tip",
    "history.log.columns.total": "Toplam",
    "history.log.columns.items": "Kalem / Not",
    "history.summary.table.date": "Tarih & Saat",
    "history.summary.table.saleType": "Satış türü",
    "history.summary.table.items": "Ürünler",
    "history.transactionNumber": "İşlem #{id}",
    "history.transactionItemsCount": "{count} öğe",
    "history.detail.customer": "Müşteri",
    "history.detail.status": "Durum",
    "history.detail.itemsTitle": "Ürünler",
    "history.detail.itemsSubtotal": "Ürünler ara toplamı",
    "history.detail.noItems": "Bu işlem için kayıtlı ürün yok.",
    "history.noMatches": "Aramanızla eşleşen işlem yok.",
    "history.filter.all": "Tümü",
    "history.filter.paid": "Peşin",
    "history.filter.debt": "Borç",
    "history.empty": "Kayıtlı işlem yok",
    "history.receipt": "Fişi görüntüle",
    "notFound.title": "Sayfa bulunamadı",
    "notFound.message": "Aradığınız sayfa mevcut değil.",
    "notFound.back": "Ana sayfaya dön",
    "settings.title": "Ayarlar ve Veri",
    "settings.backup.title": "Veritabanı Yedekleme",
    "settings.backup.description": "Verilerinizi dışa aktarın ve içe aktarın",
    "settings.backup.filenamePrompt": "Dosya adı seç",
    "settings.backup.export": "Veritabanını JSON olarak dışa aktar",
    "settings.backup.import": "Veritabanını JSON'dan içe aktar",
    "settings.backup.note": "Tüm veriler tarayıcınızda yerel olarak saklanır. Diğer cihazda geri yüklemek için dışa aktarma ve içe aktarma işlemlerini kullanın.",
    "settings.auth.title": "Kimlik Doğрulama",
    "settings.auth.description": "Mevcut oturumunuzu yönetin.",
    "settings.auth.signedInAs": "{user} olarak giriş yapıldı",
    "settings.auth.signOut": "Çıkış yap",
    "settings.auth.unknownUser": "bilinmeyen kullanıcı",
    "settings.about.title": "Hakkında",
    "settings.about.app": "Uygulama",
    "settings.about.version": "Sürüm",
    "settings.about.storage": "Depolama",
    "settings.toast.exportSuccess": "Veritabanı başarıyla dışa aktarıldı",
    "settings.toast.exportError": "Veritabanı dışa aktarılamadı",
    "settings.toast.importSuccess": "Veritabanı içe aktarıldı. Yeniden yükleniyor...",
    "settings.toast.importError": "Veritabanı içe aktarılamadı",
    "settings.toast.readError": "Dosya okunamadı",
    "toast.genericError": "Bir şeyler ters gitti",
  },
  ru: {
    "common.cancel": "Отмена",
    "app.name": "Офлайн склад",
    "app.tagline": "Управление запасами и продажами для локальных магазинов",
    "app.initializing": "Инициализация базы данных...",
    "nav.depot": "Склад",
    "nav.sales": "Продажи",
    "nav.customers": "Клиенты",
    "nav.shopping": "Закупки",
    "nav.history": "История",
    "nav.settings": "Настройки",
    "layout.theme": "Тема",
    "layout.language": "Язык",
    "layout.defaultTitle": "Magazin Proekt",
    "theme.light": "Светлая",
    "theme.dark": "Тёмная",
    "theme.system": "Системная",
    "language.english": "English",
    "language.turkish": "Türkçe",
    "language.russian": "Русский",
    "login.title": "Офлайн склад",
    "login.subtitle": "Войдите, используя ник и пароль, чтобы продолжить.",
    "login.nickname": "Ник",
    "login.nickname.placeholder": "Введите ваш ник",
    "login.password": "Пароль",
    "login.password.placeholder": "Введите ваш пароль",
    "login.remember": "Запомнить меня на этом устройстве",
    "login.submit": "Войти",
    "login.submitting": "Вход...",
    "login.signup.question": "Нужна учётная запись?",
    "login.signup.link": "Зарегистрироваться",
    "login.validation": "Ник и пароль обязательны",
    "signup.title": "Создать аккаунт",
    "signup.subtitle": "Настройте данные администратора для защиты магазина.",
    "signup.nickname": "Ник",
    "signup.nickname.placeholder": "Выберите ник",
    "signup.password": "Пароль",
    "signup.password.placeholder": "Придумайте пароль",
    "signup.confirmPassword": "Подтвердите пароль",
    "signup.confirmPassword.placeholder": "Повторите пароль",
    "signup.submit": "Создать аккаунт",
    "signup.submitting": "Создание аккаунта...",
    "signup.haveAccount": "Уже есть аккаунт?",
    "signup.login": "Войти",
    "signup.passwordMismatch": "Пароли не совпадают",
    "signup.validation": "Ник и пароль обязательны",
    "signup.passwordLength": "Пароль должен содержать не менее 6 символов",
    "depot.title": "Magazin Proekt",
    "depot.search.placeholder": "Поиск товаров...",
    "depot.add": "Добавить",
    "depot.addProduct": "Добавить товар",
    "depot.editProduct": "Редактировать товар",
    "depot.form.name": "Название",
    "depot.form.barcode": "Штрихкод/SKU",
    "depot.form.category": "Категория",
    "depot.form.buyPrice": "Закупочная цена",
    "depot.form.sellPrice": "Цена продажи",
    "depot.form.quantity": "Количество",
    "depot.form.minStock": "Мин. запас",
    "depot.form.save": "Сохранить",
    "depot.export": "Экспорт",
    "depot.export.filename": "tovary",
    "depot.export.sheetName": "Товары",
    "depot.filter.all": "Все",
    "depot.filter.category": "Категория",
    "depot.filter.searchPlaceholder": "Поиск категорий...",
    "depot.filter.noResults": "Категории не найдены",
    "depot.filter.uncategorized": "Без категории",
    "depot.actions.deleteAll": "Удалить все товары",
    "depot.badge.low": "Мало",
    "depot.price.buy": "Покупка:",
    "depot.price.sell": "Продажа:",
    "depot.totals.buy": "Итого закуп",
    "depot.totals.sell": "Итого продажа",
    "depot.totals.monthSelector": "Месяц продаж",
    "depot.totals.clearMonth": "Показать все",
    "depot.totals.monthlySales": "Продажи за месяц",
    "depot.stock": "на складе",
    "depot.empty": "Товары не найдены",
    "depot.toast.added": "Товар успешно добавлен",
    "depot.toast.updated": "Товар успешно обновлён",
    "depot.toast.savedError": "Не удалось сохранить товар",
    "depot.toast.increased": "Запас увеличен",
    "depot.toast.decreased": "Запас уменьшен",
    "depot.toast.deleted": "Товар удалён",
    "depot.toast.allDeleted": "Все товары удалены",
    "depot.toast.noProductsToDelete": "Нет товаров для удаления.",
    "depot.toast.noExport": "Нет товаров для экспорта",
    "depot.confirm.delete": "Удалить товар \"{name}\" из склада?",
    "depot.confirm.deleteAll": "Удалить все товары и убрать их из списков покупок? Это действие нельзя отменить.",
    "depot.export.name": "Название",
    "depot.export.barcode": "Штрихкод",
    "depot.export.category": "Категория",
    "depot.export.buyPrice": "Закупочная цена",
    "depot.export.sellPrice": "Цена продажи",
    "depot.export.quantity": "Количество",
    "depot.export.minStock": "Минимальный запас",
    "sales.title": "Продажи",
    "sales.searchProducts": "Поиск товаров...",
    "sales.openCatalog": "Добавить товары",
    "sales.cartSearch": "Поиск по корзине...",
    "sales.cart": "Корзина",
    "sales.noItems": "В корзине нет товаров",
    "sales.totals": "Итоги",
    "sales.total": "Итого",
    "sales.paid": "Оплачено",
    "sales.debt": "Долг",
    "sales.saleType": "Тип продажи",
    "sales.saleType.paid": "Полностью оплачено",
    "sales.saleType.debt": "В долг",
    "sales.customer": "Клиент",
    "sales.customer.select": "Выбрать клиента",
    "sales.customer.new": "Добавить клиента",
    "sales.customer.none": "Клиенты не найдены",
    "sales.newCustomer.title": "Новый клиент",
    "sales.newCustomer.name": "Имя",
    "sales.newCustomer.phone": "Телефон",
    "sales.newCustomer.notes": "Заметки",
    "sales.newCustomer.submit": "Создать",
    "sales.newCustomer.cancel": "Отмена",
    "sales.complete": "Завершить продажу",
    "sales.clear": "Очистить корзину",
    "sales.toast.noStock": "Недостаточно запаса",
    "sales.toast.added": "Добавлено в корзину",
    "sales.toast.nameRequired": "Требуется имя клиента",
    "sales.toast.created": "Клиент успешно создан",
    "sales.toast.createError": "Не удалось создать клиента",
    "sales.toast.empty": "Корзина пуста",
    "sales.toast.customerRequired": "Выберите клиента для продажи в долг",
    "sales.toast.failed": "Не удалось завершить продажу",
    "sales.toast.completed": "Продажа успешно сохранена",
    "sales.debtNote": "Продажи в долг требуют выбора клиента и будут отслеживаться до полного погашения.",
    "sales.customerTotal": "Итого для {name}",
    "sales.unitPrice": "{price} за единицу",
    "sales.priceLabel": "\u0426\u0435\u043d\u0430",
    "sales.noMatches": "В корзине нет товаров по вашему запросу.",
    "sales.receipt.title": "Чек продажи",
    "sales.receipt.customer": "Клиент",
    "sales.receipt.date": "Дата",
    "sales.receipt.cashier": "Кассир",
    "sales.receipt.items": "Товары",
    "sales.receipt.total": "Итого",
    "sales.receipt.paid": "Оплачено",
    "sales.receipt.debt": "Долг",
    "sales.receipt.status": "Статус",
    "customers.title": "Клиенты",
    "customers.search": "Поиск клиентов...",
    "customers.add": "Добавить клиента",
    "customers.actions.deleteAll": "Удалить всех клиентов",
    "customers.form.name": "Имя",
    "customers.form.phone": "Телефон",
    "customers.form.notes": "Заметки",
    "customers.form.save": "Сохранить",
    "customers.empty": "Клиенты не найдены",
    "customers.totalSpent": "Всего потрачено",
    "customers.totalPaid": "Всего оплачено",
    "customers.totalDebt": "Всего долгов",
    "customers.transactions": "Сделки",
    "customers.noTransactions": "Сделок ещё нет",
    "customers.totalTransactions": "Всего сделок",
    "customers.dialog.edit": "Редактировать клиента",
    "customers.dialog.add": "Добавить клиента",
    "customers.export.all": "Экспортировать все",
    "customers.export.single": "Экспортировать отчёт",
    "customers.export.overviewFilename": "customers_overview",
    "customers.export.overviewSheet": "Клиенты",
    "customers.export.summarySheet": "Сводка",
    "customers.export.transactionsSheet": "Сделки",
    "customers.export.reportSuffix": "otchet",
    "customers.export.columns.customerId": "ID клиента",
    "customers.export.columns.customerName": "Имя клиента",
    "customers.export.columns.customer": "Клиент",
    "customers.export.columns.phone": "Телефон",
    "customers.export.columns.notes": "Заметки",
    "customers.export.columns.totalTransactions": "Количество сделок",
    "customers.export.columns.totalSpent": "Всего потрачено",
    "customers.export.columns.fullyPaid": "Оплачено полностью",
    "customers.export.columns.outstandingDebt": "Задолженность",
    "customers.export.columns.transactionId": "ID сделки",
    "customers.export.columns.date": "Дата",
    "customers.export.columns.status": "Статус оплаты",
    "customers.export.columns.transactionTotal": "Сумма сделки",
    "customers.export.columns.item": "Позиция",
    "customers.export.columns.quantity": "Количество",
    "customers.export.columns.unitPrice": "Цена",
    "customers.export.columns.lineTotal": "Сумма строки",
    "customers.status.debt": "Долг",
    "customers.status.paid": "Полностью оплачено",
    "customers.toast.updated": "Клиент обновлён",
    "customers.toast.added": "Клиент добавлен",
    "customers.toast.saveError": "Не удалось сохранить клиента",
    "customers.toast.statusUpdated": "Статус оплаты обновлён",
    "customers.toast.amountUpdated": "Платёж обновлён",
    "customers.toast.invalidAmount": "Введите корректную сумму",
    "customers.toast.statusError": "Не удалось обновить статус оплаты",
    "customers.toast.deleted": "Клиент удалён",
    "customers.toast.allDeleted": "Все клиенты удалены",
    "customers.toast.noCustomersToDelete": "Нет клиентов для удаления.",
    "customers.toast.noExport": "Нет клиентов для экспорта",
    "customers.confirm.delete": "Удалить клиента \"{name}\"? Это удалит его транзакции.",
    "customers.confirm.deleteAll": "Удалить всех клиентов и их сделки? Это действие нельзя отменить.",
    "customers.transactions.hide": "Скрыть сделки",
    "shopping.title": "Списки закупок",
    "shopping.stats.active": "Активные списки",
    "shopping.stats.pending": "Незавершённые позиции",
    "shopping.stats.outstanding": "Незакрытый бюджет",
    "shopping.monthly.subtitle": "Месячный список пополнения",
    "shopping.monthly.pending": "В ожидании: {count}",
    "shopping.monthly.view": "Открыть список",
    "shopping.monthly.transfer": "Перенести товары",
    "shopping.monthly.helper": "Продажи автоматически добавляют купленные кол-ва для след. закупки.",
    "shopping.intro.heading": "Списки закупок",
    "shopping.intro.description": "Создавайте отдельные страницы для каждого плана закупок и держите их под рукой.",
    "shopping.actions.newList": "Новый список",
    "shopping.actions.deleteAll": "Удалить все списки",
    "shopping.dialog.editTitle": "Редактировать список",
    "shopping.dialog.createTitle": "Создать список",
    "shopping.dialog.description": "Группируйте закупки для пополнения склада или особых заказов клиентов.",
    "shopping.form.title": "Название",
    "shopping.form.type": "Тип",
    "shopping.form.typePlaceholder": "Выберите тип",
    "shopping.form.status": "Статус",
    "shopping.form.statusPlaceholder": "Выберите статус",
    "shopping.form.priority": "Приоритет",
    "shopping.form.priorityPlaceholder": "Выберите приоритет",
    "shopping.form.expectedDate": "Ожидаемая дата",
    "shopping.form.customer": "Клиент",
    "shopping.form.customerPlaceholder": "Выберите клиента",
    "shopping.form.customerUnassigned": "Не назначен",
    "shopping.form.notes": "Заметки",
    "shopping.form.notesPlaceholder": "Дополнительные детали, поставщик, напоминания о доставке...",
    "shopping.form.submit.save": "Сохранить изменения",
    "shopping.form.submit.create": "Создать список",
    "shopping.form.validation.title": "Требуется название списка",
    "shopping.search.label": "Поиск",
    "shopping.search.placeholder": "Поиск по названию или клиенту",
    "shopping.filter.label": "Фильтр",
    "shopping.filter.placeholder": "Фильтровать списки",
    "shopping.filter.all": "Все списки",
    "shopping.filter.restock": "Пополнение склада",
    "shopping.filter.customer": "Заказы клиентов",
    "shopping.filter.completed": "Завершённые",
    "shopping.empty": "Списков по выбранным фильтрам нет. Измените параметры поиска.",
    "shopping.type.restock": "Пополнение склада",
    "shopping.type.customerOrder": "Заказ клиента",
    "shopping.type.monthlyRestock": "Месячный запас",
    "shopping.status.active": "Активный",
    "shopping.status.completed": "Завершённый",
    "shopping.status.archived": "Архив",
    "shopping.priority.high": "Высокий",
    "shopping.priority.medium": "Средний",
    "shopping.priority.low": "Низкий",
    "shopping.priority.badge": "Приоритет: {priority}",
    "shopping.list.customerLabel": "Клиент: {name}",
    "shopping.list.due": "Срок {date}",
    "shopping.list.summary.items": "{count} позиций",
    "shopping.list.summary.pending": "{count} в работе",
    "shopping.list.summary.budget": "Бюджет: {amount}",
    "shopping.list.viewDetails": "Открыть детали",
    "shopping.actions.edit": "Редактировать",
    "shopping.actions.reopen": "Возобновить список",
    "shopping.actions.markCompleted": "Отметить завершённым",
    "shopping.actions.delete": "Удалить",
    "shopping.actions.deleteList": "Удалить список",
    "shopping.actions.export": "Экспорт",
    "shopping.actions.back": "Назад к спискам закупок",
    "shopping.toast.listUpdated": "Список закупок обновлён",
    "shopping.toast.listCreated": "Список закупок создан",
    "shopping.toast.listSaveError": "Не удалось сохранить список закупок",
    "shopping.toast.listDeleted": "Список закупок удалён",
    "shopping.toast.listCompleted": "Список отмечен как завершённый",
    "shopping.toast.itemsTransferred": "Обновлено товаров на складе: {count}",
    "shopping.toast.listReopened": "Список вновь открыт",
    "shopping.toast.allDeleted": "Все списки покупок удалены",
    "shopping.toast.noListsToDelete": "Нет списков покупок для удаления.",
    "shopping.confirm.deleteList": "Удалить список \"{title}\" и все его позиции?",
    "shopping.confirm.deleteAll": "Удалить все списки закупок и их позиции? Это действие нельзя отменить.",
    "shopping.detail.title": "Список закупок",
    "shopping.detail.invalidUrl": "Недействительная ссылка на список закупок.",
    "shopping.detail.notFound": "Этот список закупок не найден.",
    "shopping.detail.actions.manage": "Управление списком",
    "shopping.detail.actions.editDetails": "Редактировать данные",
    "shopping.detail.toast.listMissing": "Список закупок не найден",
    "shopping.detail.toast.itemNameRequired": "Требуется название позиции",
    "shopping.detail.toast.itemUpdated": "Позиция списка закупок обновлена",
    "shopping.detail.toast.itemCreated": "Позиция добавлена в список закупок",
    "shopping.detail.toast.itemSaveError": "Не удалось сохранить позицию",
    "shopping.detail.toast.itemDeleted": "Позиция удалена",
    "shopping.detail.toast.listSaveError": "Не удалось обновить список закупок",
    "shopping.detail.confirm.deleteItem": "Удалить \"{name}\" из этого списка?",
    "shopping.itemStatus.completed": "Завершено",
    "shopping.itemStatus.pending": "В работе",
    "shopping.detail.stats.totalEstimated": "Оценочный итог",
    "shopping.detail.stats.pendingBudget": "Незакрытый бюджет",
    "shopping.detail.stats.progress": "Прогресс",
    "shopping.detail.stats.pendingItems": "В работе",
    "shopping.detail.stats.completedItems": "Завершено",
    "shopping.detail.stats.created": "Создан",
    "shopping.detail.sections.items": "Позиции",
    "shopping.detail.dialog.addItem": "Добавить позицию",
    "shopping.detail.dialog.editItem": "Редактировать позицию",
    "shopping.detail.dialog.itemDescription": "Свяжите со складскими товарами или добавьте короткие заметки по закупке.",
    "shopping.detail.form.depotProduct": "Товар со склада",
    "shopping.detail.form.productPlaceholder": "Выберите товар",
    "shopping.detail.form.customItem": "Своя позиция",
    "shopping.detail.form.name": "Название",
    "shopping.detail.form.quantity": "Количество",
    "shopping.detail.form.unit": "Единица",
    "shopping.detail.form.estimatedUnitCost": "Оценочная себестоимость",
    "shopping.detail.form.notesPlaceholder": "Подсказки по поставщику, варианты, напоминания о доставке...",
    "shopping.detail.form.submit.add": "Добавить позицию",
    "shopping.detail.form.submit.save": "Сохранить изменения",
    "shopping.detail.pending.title": "Позиции в работе",
    "shopping.detail.pending.empty": "Все готово! Добавьте новые позиции, чтобы пополнить очередь закупок.",
    "shopping.detail.items.linkedToDepot": "Связано со складом",
    "shopping.detail.items.quantityPrefix": "Кол-во:",
    "shopping.detail.items.productInfo": "На складе: {stock} • Цена закупки: {price}",
    "shopping.detail.items.costSummary": "Себестоимость: {unitCost} • Оценочная сумма: {total}",
    "shopping.detail.items.addedOn": "Добавлено {date}",
    "shopping.detail.items.finalCost": "Итоговая сумма: {total}",
    "shopping.detail.items.completedOn": "Завершено {date}",
    "shopping.detail.completed.title": "Завершённые",
    "shopping.detail.completed.empty": "Позиции появятся здесь после отметки как завершённые.",
    "shopping.detail.dialog.listTitle": "Редактировать список закупок",
    "shopping.detail.dialog.listDescription": "Обновите детали этого списка закупок.",
    "shopping.detail.export.summarySheet": "Итоги",
    "shopping.detail.export.itemsSheet": "Позиции",
    "shopping.detail.export.columns.listName": "Название списка",
    "shopping.detail.export.columns.type": "Тип",
    "shopping.detail.export.columns.status": "Статус",
    "shopping.detail.export.columns.priority": "Приоритет",
    "shopping.detail.export.columns.totalItems": "Всего позиций",
    "shopping.detail.export.columns.pendingItems": "В работе",
    "shopping.detail.export.columns.completedItems": "Завершено",
    "shopping.detail.export.columns.estimatedTotal": "Оценочная сумма",
    "shopping.detail.export.columns.pendingBudget": "Незакрытый бюджет",
    "shopping.detail.export.columns.customer": "Клиент",
    "shopping.detail.export.columns.dueDate": "Срок",
    "shopping.detail.export.columns.notes": "Заметки",
    "shopping.detail.export.columns.itemName": "Название",
    "shopping.detail.export.columns.itemQuantity": "Количество",
    "shopping.detail.export.columns.itemUnit": "Ед. изм.",
    "shopping.detail.export.columns.itemUnitCost": "Себестоимость",
    "shopping.detail.export.columns.itemEstimatedTotal": "Оценочная сумма",
    "shopping.detail.export.columns.itemLinkedProduct": "Связанный товар",
    "shopping.detail.export.columns.itemStatus": "Статус",
    "shopping.detail.export.columns.created": "Создано",
    "customers.transactions.view": "Показать сделки",
    "customers.transactions.transactionNumber": "Сделка №{id}",
    "customers.transactions.setStatus": "Изменить статус на {status}",
    "customers.transactions.adjustAmount": "Изменить сумму",
    "customers.transactions.adjustPrompt": "Введите оплату (остаток {amount})",
    "customers.transactions.outstanding": "Остаток: {amount}",
    "customers.transactions.itemsCount": "{count} поз.",
    "customers.transactions.itemSummary": "{name} • {quantity} × {price}",
    "customers.noMatches": "Клиенты не найдены по запросу.",
    "history.title": "История",
    "history.search": "Поиск по операциям...",
    "history.export.all": "Экспортировать все",
    "history.export.summary": "Экспортировать сводку",
    "history.export.filename": "istoriya_operatsiy",
    "history.export.summarySheet": "Сводка",
    "history.export.transactionsSheet": "Сделки",
    "history.toast.noExport": "Нет операций для экспорта",
    "history.toast.invalidPeriod": "Выберите корректный период",
    "history.toast.noPeriodTransactions": "В выбранном периоде нет операций",
    "history.toast.summaryExported": "Сводка успешно экспортирована",
    "history.summary.title": "Экспорт сводки",
    "history.summary.description": "Выберите период, чтобы выгрузить краткий отчёт о продажах.",
    "history.summary.periodLabel": "Период",
    "history.summary.periodPlaceholder": "Выберите период",
    "history.summary.period.day": "День",
    "history.summary.period.week": "Неделя",
    "history.summary.period.month": "Месяц",
    "history.summary.period.year": "Год",
    "history.summary.dayLabel": "Выберите день",
    "history.summary.weekLabel": "Выберите неделю",
    "history.summary.monthLabel": "Выберите месяц",
    "history.summary.yearLabel": "Выберите год",
    "history.summary.period": "Период",
    "history.summary.start": "Начало",
    "history.summary.end": "Конец",
    "history.summary.totalAmount": "Общая сумма",
    "history.summary.preview": "Диапазон",
    "history.summary.previewInvalid": "Выберите правильный период",
    "history.export.filenamePrompt": "Выберите имя файла",
    "history.export.logSheet": "Журнал",
    "history.log.saleDebt": "Продажа (в долг)",
    "history.log.salePaid": "Продажа (оплачено)",
    "history.log.payment": "Платёж",
    "history.log.adjustment": "Корректировка",
    "history.log.paymentNote": "Оплата по сделке #{id}",
    "history.log.columns.time": "Время",
    "history.log.columns.customer": "Клиент",
    "history.log.columns.type": "Тип",
    "history.log.columns.total": "Сумма",
    "history.log.columns.items": "Позиции / Примечание",
    "history.summary.table.date": "Дата и время",
    "history.summary.table.saleType": "Тип продажи",
    "history.summary.table.items": "Позиции",
    "history.transactionNumber": "Сделка №{id}",
    "history.transactionItemsCount": "{count} поз.",
    "history.detail.customer": "Клиент",
    "history.detail.status": "Статус",
    "history.detail.itemsTitle": "Позиции",
    "history.detail.itemsSubtotal": "Итого по позициям",
    "history.detail.noItems": "Для этой сделки позиции не записаны.",
    "history.noMatches": "Операции не найдены.",
    "history.filter.all": "Все",
    "history.filter.paid": "Оплачено",
    "history.filter.debt": "Долг",
    "history.empty": "История пуста",
    "history.receipt": "Открыть чек",
    "notFound.title": "Страница не найдена",
    "notFound.message": "Страница, которую вы ищете, не существует.",
    "notFound.back": "Вернуться на главную",
    "settings.title": "Настройки и данные",
    "settings.backup.title": "Резервное копирование",
    "settings.backup.description": "Экспорт и импорт данных",
    "settings.backup.filenamePrompt": "Выберите имя файла",
    "settings.backup.export": "Экспортировать базу в JSON",
    "settings.backup.import": "Импортировать базу из JSON",
    "settings.backup.note": "Все данные хранятся локально в браузере. Используйте экспорт для резервных копий и импорт для восстановления на другом устройстве.",
    "settings.auth.title": "Аутентификация",
    "settings.auth.description": "Управляйте текущей сессией.",
    "settings.auth.signedInAs": "Вы вошли как {user}",
    "settings.auth.signOut": "Выйти",
    "settings.auth.unknownUser": "неизвестный пользователь",
    "settings.about.title": "О приложении",
    "settings.about.app": "Приложение",
    "settings.about.version": "Версия",
    "settings.about.storage": "Хранилище",
    "settings.toast.exportSuccess": "База успешно экспортирована",
    "settings.toast.exportError": "Не удалось экспортировать базу",
    "settings.toast.importSuccess": "База импортирована. Перезагрузка...",
    "settings.toast.importError": "Не удалось импортировать базу",
    "settings.toast.readError": "Не удалось прочитать файл",
    "toast.genericError": "Что-то пошло не так",
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") {
      return "en";
    }
    const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null;
    return stored ?? "en";
  });

  useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
  }, []);

  const translate = useCallback<LanguageContextValue["t"]>((key, options) => {
    const dictionary = translations[language] ?? translations.en;
    const fallback = options?.defaultValue ?? key;
    const template = dictionary[key] ?? translations.en[key] ?? fallback;
    if (!options?.values) {
      return template;
    }
    return Object.entries(options.values).reduce((acc, [token, value]) => {
      return acc.replace(new RegExp(`{${token}}`, "g"), String(value));
    }, template);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    availableLanguages: (Object.keys(languageLabels) as Language[]).map(value => ({
      value,
      label: languageLabels[value],
    })),
    t: translate,
  }), [language, setLanguage, translate]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguageContext(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguageContext must be used within a LanguageProvider");
  }
  return context;
}

